<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JAJ.Packages.GLFWNet" Version="1.0.3" />
    <PackageReference Include="JAJ.Packages.OpenTK5" Version="1.0.0" />
    <PackageReference Include="JAJ.Packages.TinyFileDialogs" Version="1.0.0" />
    <PackageReference Include="JAJ.Packages.MiniAudioEx" Version="3.3.3" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
  </ItemGroup>

</Project>
